### ISSUE TITLE
Mark all read not working

### ISSUE THREAD

**Issue by oddpixels** [kevinpapst/freshrss-fever-api#2]
Hi,
First of all thanks for your work. I just tried your implementation with unread and Reeder on iOS.
Syncing works fine but whenever I try to mark all unread article as read, it is not synced to my FreshRSS Server. With the next sync, all items come back as unread.
Marking groups or single entries as read works flawlessly.

I’m running FreshRSS 1.10.2

**Comment by kevinpapst** [comment]
Thanks for the info! I'll look into it when I have the time

**Comment by helpsterTee** [comment]
Reeder 3 is posting this when marking all unread as read:

``` 
Reeder/3.1.21 CFNetwork/897.10 Darwin/17.5.0: {"api":"","id":"0","mark":"group","as":"read","api_key":"xxx","before":"1525065745","FreshRSS":"xxx"}
```

**Comment by Alkarex** [comment]
Fever API has been implemented in https://github.com/FreshRSS/FreshRSS/pull/1836 and available in the /dev branch of FreshRSS. We are looking for testers, so do not hesitate to go ahead and report your experience.

**Comment by kevinpapst** [comment]
Please repost your issue in the FreshRSS issue tracker, I'll archive this repository now - as the code moved to FreshRSS core.
